### ISSUE TITLE
Error while trying core.getInfo();

### ISSUE THREAD

**Issue by Rodricity** [AKORA-Studios/MoodleClient#2]
Hi!

I've tested the package and something seems to be incorrectly handled with axios and form-data, I've made a PR to replace that dependency with native methods.

Im posting this here as an example of the error.

```
import { Client } from 'akora-moodle';

async function test() {
    const client = await Client.init({
        wwwroot: 'http://localhost/moodle',
        token: "22a032089f21507a1c002f1736ad09e9",
        service: 'moodle_mobile_app',
        logger: true
    });

    const contenido = await client.core.getInfo();
    console.log(contenido);
    return true;
}

test();
```

![Captura de pantalla -2021-03-12 15-46-47](https://user-images.githubusercontent.com/26635983/110984664-34b49300-834a-11eb-93cc-d827b1e07b76.png)

**Comment by Rodricity** [comment]
With pull request #4 the error is fixed.

![Captura de pantalla -2021-03-12 16-00-13](https://user-images.githubusercontent.com/26635983/110986339-4eef7080-834c-11eb-9e53-2f8ef8433cf6.png)

**Comment by A-K-O-R-A** [comment]
Thanks, this was a known issue, but we didn't have time to implement a fix yet. So thank you for your effort, I will have a look at the pull request and do some quick tests to verify it works with complex data like arrays too.

**Comment by A-K-O-R-A** [comment]
If you have no further problems, I would close this issue, thank you for your contribution, and I hope you have no more issues with this package.
